---
- hosts: all
  tasks:
  - name: Remove repository (and clean up left-over metadata)
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
      - "/etc/yum.repos.d/*"

  - name: generation yumrepo
    template:
      src: templates/harbor.repo.j2
      dest: /etc/yum.repos.d/harbor.repo

  - name: make yum cache
    yum: 
      update_cache: true

  - name: disabled selinux
    selinux:
      state: disabled

  - name: start firewalld
    systemd:
      name: firewalld
      enabled: true
      state: started

  - name: config firewalld
    shell: |
      firewall-cmd --set-default-zone=trusted
      firewall-cmd --complete-reload

