---
- hosts: harbor
  tasks: 
  - name: install docker
    yum:
      disablerepo: '*'
      enablerepo: wise2c
      update_cache: true
      state: present
      name: '{{ item }}'
    with_items:
    - rsync
    - jq
    - docker
    - python-docker-py
    - docker-compose

  - name: check docker
    script: scripts/check_docker.sh {{ registry }}
    register: check_output

  - block:    
    - name: clear docker config
      copy:
        content: ''
        dest: '{{ item }}'
      with_items:
      - /etc/sysconfig/docker
      - /etc/sysconfig/docker-storage
      - /etc/sysconfig/docker-storage-setup
      - /etc/sysconfig/docker-network

    - name: distribute docker config
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
      - { src: 'templates/daemon.json.j2', dest: '/etc/docker/daemon.json' }

    - name: reload & restart docker
      systemd:
        name: docker
        daemon_reload: true
        enabled: true
        state: restarted

    - name: set sysctl
      sysctl:
        name: '{{ item }}'
        value: 1
        state: present
        reload: true
      with_items:
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables
    when: check_output.stdout != 'true'
