---
- hosts: glusterfs
  tasks: 
  - name: make gfs dir
    file:
      path: '{{ item }}'
      state: directory
      mode: 0755
    with_items:
      - '{{ brick_dir }}'

  - name: install GlusterFS
    yum: 
      name: glusterfs-server
      state: present

  - name: enable glusterd
    systemd:
      name: glusterd
      state: started
      enabled: yes

  - name: create gluster volume
    gluster_volume:
      state: present
      name: gv0
      bricks: "{{ brick_dir }}"
      rebalance: yes
      cluster: "{{ groups.glusterfs | join(',') }}"
      force: yes
    run_once: true

  - name: start gluster volume
    gluster_volume:
      state: started
      name: gv0

  - name: install keepalived
    yum:
      name: keepalived
      state: present

  - name: config keepalived
    template:
      src: templates/keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf

  - name: enable keepalived
    systemd:
      name: keepalived
      state: started
      enabled: yes

