---
- hosts: harbor
  vars:
  tasks: 
  - name: stop & rm registry
    docker_service:
      project_src: '{{ cpath }}/harbor'
      state: absent
      remove_volumes: true
    ignore_errors: yes
  
  - name: clean registry directory
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - "/var/log/harbor"
    - "{{ hapath }}/ca_download"
    - "{{ hapath }}/config"
    - "{{ hapath }}/job_logs"
    - "{{ hapath }}/psc"
    - "{{ hapath }}/registry"
    - "{{ hapath }}/secretkey"
    - "{{ cpath  }}/harbor"
