---
- hosts: harbor
  vars:
  - cpath: /data
  - version: v1.5.3
  - hapath: /data/harborHA 
  tasks: 
  - name: shutdown keepalived
    systemd:
      name: keepalived
      state: stopped
      enabled: no
    ignore_errors: yes
    tags:
      - keepalived

  - name: remove keepalived
    yum:
      name: keepalived
      state: absent
    tags:
      - keepalived

  - name: shutdown haproxy
    systemd:
      name: haproxy
      state: stopped
      enabled: no
    ignore_errors: yes
    tags:
      - haproxy

  - name: remove haproxy
    yum:
      name: haproxy
      state: absent
    tags:
      - haproxy

  - name: stop & rm registry
    docker_service:
      project_src: '{{ cpath }}/harbor'
      state: absent
      remove_volumes: true
  
  - name: clean registry directory
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - "{{ hapath }}/*"
    - "{{ cpath  }}/harbor"

  - name: Ensure Gluster volume is mounted.
    mount:
      path: "{{ hapath }}"
      src: "{{ gfs_ip }}:/gv0"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: absent
    tags:
      - umount

